import { Realm } from '../types/Realm';

export const REALMS: Realm[] = [
  {
    id: 'arrays', name: 'Foundation Forest', icon: '🌲', pattern: 'Arrays & Basics',
    color: '#4ade80', group: 'Foundation Forest', month: 1,
    artifact: { icon: '🗡️', name: 'Iron Blade', desc: 'Forged from the ore of every array traversal mastered' },
    lore: 'The primordial forest where all patterns were born. Master arrays to lay the foundation.',
    questions: [
      { id: 'a1', name: 'Two Sum', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/two-sum/' },
      { id: 'a2', name: 'Best Time to Buy and Sell Stock', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
      { id: 'a3', name: 'Contains Duplicate', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/contains-duplicate/' },
      { id: 'a4', name: 'Product of Array Except Self', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/product-of-array-except-self/' },
      { id: 'a5', name: 'Maximum Subarray', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/maximum-subarray/' },
      { id: 'a6', name: 'Maximum Product Subarray', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/maximum-product-subarray/' },
      { id: 'a7', name: 'Find Minimum in Rotated Sorted Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
      { id: 'a8', name: 'Search in Rotated Sorted Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
      { id: 'a9', name: '3Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/3sum/' },
      { id: 'a10', name: 'Container With Most Water', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/container-with-most-water/' },
      { id: 'a11', name: 'Move Zeroes', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/move-zeroes/' },
      { id: 'a12', name: 'Rotate Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/rotate-array/' },
      { id: 'a13', name: 'Next Permutation', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/next-permutation/' },
      { id: 'a14', name: 'Majority Element', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/majority-element/' },
      { id: 'a15', name: 'Pascal\'s Triangle', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/pascals-triangle/' },
    ]
  },
  {
    id: 'hashing', name: 'Memory Caverns', icon: '💎', pattern: 'Hashing',
    color: '#9b7eff', group: 'Foundation Forest', month: 1,
    artifact: { icon: '💠', name: 'Memory Crystal', desc: 'Allows instant recall of any stored truth' },
    lore: 'Deep caverns where knowledge is stored and retrieved in the blink of an eye.',
    questions: [
      { id: 'h1', name: 'Valid Anagram', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/valid-anagram/' },
      { id: 'h2', name: 'Group Anagrams', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/group-anagrams/' },
      { id: 'h3', name: 'Top K Frequent Elements', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/top-k-frequent-elements/' },
      { id: 'h4', name: 'Encode and Decode Strings', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/encode-and-decode-strings/' },
      { id: 'h5', name: 'Longest Consecutive Sequence', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
      { id: 'h6', name: 'Valid Sudoku', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/valid-sudoku/' },
      { id: 'h7', name: 'Subarray Sum Equals K', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
      { id: 'h8', name: 'Two Sum II - Input Array Is Sorted', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
      { id: 'h9', name: 'Ransom Note', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/ransom-note/' },
      { id: 'h10', name: 'Isomorphic Strings', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/isomorphic-strings/' },
      { id: 'h11', name: 'Word Pattern', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/word-pattern/' },
      { id: 'h12', name: 'Find All Anagrams in a String', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
    ]
  },
  {
    id: 'twoptr', name: 'Twin River', icon: '🌊', pattern: 'Two Pointers',
    color: '#4fc3f7', group: 'Foundation Forest', month: 1,
    artifact: { icon: '🧭', name: 'Explorer Compass', desc: 'Always finds the optimal path through any sequence' },
    lore: 'Two rivers converging — the ancient technique of dual traversal.',
    questions: [
      { id: 'tp1', name: 'Valid Palindrome', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/valid-palindrome/' },
      { id: 'tp2', name: 'Two Sum II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
      { id: 'tp3', name: '3Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/3sum/' },
      { id: 'tp4', name: 'Container With Most Water', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/container-with-most-water/' },
      { id: 'tp5', name: 'Trapping Rain Water', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/trapping-rain-water/' },
      { id: 'tp6', name: 'Boats to Save People', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/boats-to-save-people/' },
      { id: 'tp7', name: 'Sort Colors', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/sort-colors/' },
      { id: 'tp8', name: 'Remove Duplicates from Sorted Array', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/' },
      { id: 'tp9', name: 'Remove Element', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/remove-element/' },
      { id: 'tp10', name: '4Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/4sum/' },
      { id: 'tp11', name: 'Squares of a Sorted Array', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/squares-of-a-sorted-array/' },
      { id: 'tp12', name: 'Minimum Size Subarray Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
    ]
  },
  {
    id: 'sliding', name: 'Moving Observatory', icon: '🔭', pattern: 'Sliding Window',
    color: '#fbbf24', group: 'Foundation Forest', month: 1,
    artifact: { icon: '🔮', name: 'Shifting Lens', desc: 'Reveals patterns within moving ranges of data' },
    lore: 'An observatory that scans the horizon — always watching a window of possibilities.',
    questions: [
      { id: 'sw1', name: 'Best Time to Buy and Sell Stock', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
      { id: 'sw2', name: 'Longest Substring Without Repeating Characters', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
      { id: 'sw3', name: 'Longest Repeating Character Replacement', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
      { id: 'sw4', name: 'Permutation in String', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/permutation-in-string/' },
      { id: 'sw5', name: 'Minimum Window Substring', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/minimum-window-substring/' },
      { id: 'sw6', name: 'Sliding Window Maximum', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/sliding-window-maximum/' },
      { id: 'sw7', name: 'Max Consecutive Ones III', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/max-consecutive-ones-iii/' },
      { id: 'sw8', name: 'Fruit Into Baskets', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/fruit-into-baskets/' },
      { id: 'sw9', name: 'Minimum Size Subarray Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
      { id: 'sw10', name: 'Maximum Average Subarray I', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/maximum-average-subarray-i/' },
      { id: 'sw11', name: 'Substring with Concatenation of All Words', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/' },
    ]
  },
  {
    id: 'prefix', name: 'Crystal Archives', icon: '📜', pattern: 'Prefix Sum',
    color: '#f0c060', group: 'Foundation Forest', month: 1,
    artifact: { icon: '📚', name: 'Ancient Tome', desc: 'Precomputed wisdom for answering range queries instantly' },
    lore: 'Crystallized scrolls that store the accumulated knowledge of all that came before.',
    questions: [
      { id: 'px1', name: 'Running Sum of 1d Array', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/running-sum-of-1d-array/' },
      { id: 'px2', name: 'Find Pivot Index', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/find-pivot-index/' },
      { id: 'px3', name: 'Range Sum Query - Immutable', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/range-sum-query-immutable/' },
      { id: 'px4', name: 'Subarray Sum Equals K', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
      { id: 'px5', name: 'Product of Array Except Self', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/product-of-array-except-self/' },
      { id: 'px6', name: 'Count Number of Nice Subarrays', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/count-number-of-nice-subarrays/' },
      { id: 'px7', name: 'Number of Ways to Split Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-ways-to-split-array/' },
      { id: 'px8', name: 'Maximum Size Subarray Sum Equals k', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/' },
      { id: 'px9', name: 'Contiguous Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/contiguous-array/' },
    ]
  },
  {
    id: 'bsearch', name: 'Halfmoon Mines', icon: '⛏️', pattern: 'Binary Search',
    color: '#e85d3a', group: 'Foundation Forest', month: 1,
    artifact: { icon: '⚖️', name: 'Balance Scale', desc: 'Divides any problem space in half with perfect precision' },
    lore: 'Ancient miners who discovered that halving the search space unlocks even the deepest secrets.',
    questions: [
      { id: 'bs1', name: 'Binary Search', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/binary-search/' },
      { id: 'bs2', name: 'Find Minimum in Rotated Sorted Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
      { id: 'bs3', name: 'Search in Rotated Sorted Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
      { id: 'bs4', name: 'Koko Eating Bananas', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/koko-eating-bananas/' },
      { id: 'bs5', name: 'Find Peak Element', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-peak-element/' },
      { id: 'bs6', name: 'Search a 2D Matrix', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/search-a-2d-matrix/' },
      { id: 'bs7', name: 'Median of Two Sorted Arrays', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
      { id: 'bs8', name: 'Time Based Key-Value Store', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/time-based-key-value-store/' },
      { id: 'bs9', name: 'Find First and Last Position of Element in Sorted Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/' },
      { id: 'bs10', name: 'Split Array Largest Sum', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/split-array-largest-sum/' },
      { id: 'bs11', name: 'Capacity To Ship Packages Within D Days', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/' },
      { id: 'bs12', name: 'Aggressive Cows (Search on Answer)', diff: 'Medium', xp: 15, url: 'https://www.geeksforgeeks.org/aggressive-cows-problem/' },
    ]
  },
  {
    id: 'linked', name: 'Linked Marshes', icon: '🔗', pattern: 'Linked Lists',
    color: '#4fc3f7', group: 'Data Structure Valley', month: 2,
    artifact: { icon: '⛓️', name: 'Ethereal Chain', desc: 'A chain of memory nodes that bends without breaking' },
    lore: 'A labyrinthine marsh where each stepping stone leads to the next — never random, always linked.',
    questions: [
      { id: 'll1', name: 'Reverse Linked List', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/reverse-linked-list/' },
      { id: 'll2', name: 'Merge Two Sorted Lists', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
      { id: 'll3', name: 'Reorder List', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/reorder-list/' },
      { id: 'll4', name: 'Remove Nth Node From End of List', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
      { id: 'll5', name: 'Copy List with Random Pointer', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
      { id: 'll6', name: 'Add Two Numbers', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/add-two-numbers/' },
      { id: 'll7', name: 'Linked List Cycle', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/linked-list-cycle/' },
      { id: 'll8', name: 'Find the Duplicate Number', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/find-the-duplicate-number/' },
      { id: 'll9', name: 'LRU Cache', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/lru-cache/' },
      { id: 'll10', name: 'Merge K Sorted Lists', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
      { id: 'll11', name: 'Reverse Nodes in k-Group', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },
      { id: 'll12', name: 'Middle of the Linked List', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/middle-of-the-linked-list/' },
      { id: 'll13', name: 'Palindrome Linked List', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/palindrome-linked-list/' },
      { id: 'll14', name: 'Intersection of Two Linked Lists', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/intersection-of-two-linked-lists/' },
    ]
  },
  {
    id: 'stack', name: 'Iron Tower', icon: '🏗️', pattern: 'Stack',
    color: '#9b7eff', group: 'Data Structure Valley', month: 2,
    artifact: { icon: '🛡️', name: 'Iron Shield', desc: 'A last-in, first-out defense against any problem' },
    lore: 'An iron monolith built layer by layer. Only the brave who master LIFO may climb to the top.',
    questions: [
      { id: 'st1', name: 'Valid Parentheses', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/valid-parentheses/' },
      { id: 'st2', name: 'Min Stack', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/min-stack/' },
      { id: 'st3', name: 'Evaluate Reverse Polish Notation', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
      { id: 'st4', name: 'Generate Parentheses', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/generate-parentheses/' },
      { id: 'st5', name: 'Daily Temperatures', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/daily-temperatures/' },
      { id: 'st6', name: 'Car Fleet', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/car-fleet/' },
      { id: 'st7', name: 'Largest Rectangle in Histogram', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
      { id: 'st8', name: 'Basic Calculator', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/basic-calculator/' },
      { id: 'st9', name: 'Next Greater Element I', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/next-greater-element-i/' },
      { id: 'st10', name: 'Next Greater Element II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/next-greater-element-ii/' },
      { id: 'st11', name: 'Asteroid Collision', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/asteroid-collision/' },
    ]
  },
  {
    id: 'heap', name: 'Clockwork Forge', icon: '⚙️', pattern: 'Heap / Priority Queue',
    color: '#e85d3a', group: 'Data Structure Valley', month: 2,
    artifact: { icon: '🔔', name: 'Priority Bell', desc: 'Always surfaces the most urgent task first' },
    lore: 'A mechanical forge that continuously reorganizes itself to bring the highest priority to the surface.',
    questions: [
      { id: 'hp1', name: 'Kth Largest Element in a Stream', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/' },
      { id: 'hp2', name: 'Last Stone Weight', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/last-stone-weight/' },
      { id: 'hp3', name: 'K Closest Points to Origin', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
      { id: 'hp4', name: 'Kth Largest Element in an Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
      { id: 'hp5', name: 'Task Scheduler', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/task-scheduler/' },
      { id: 'hp6', name: 'Design Twitter', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/design-twitter/' },
      { id: 'hp7', name: 'Find Median from Data Stream', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/find-median-from-data-stream/' },
      { id: 'hp8', name: 'Merge K Sorted Lists', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
      { id: 'hp9', name: 'Top K Frequent Words', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/top-k-frequent-words/' },
      { id: 'hp10', name: 'Smallest Range Covering Elements from K Lists', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/' },
    ]
  },
  {
    id: 'backtrack', name: 'Mirror Maze', icon: '🪞', pattern: 'Backtracking',
    color: '#ff6eb4', group: 'Data Structure Valley', month: 2,
    artifact: { icon: '🗝️', name: 'Maze Key', desc: 'Unlocks every path by trying and unmaking choices' },
    lore: 'A maze of infinite mirrors — you must explore every path and retreat when dead ends appear.',
    questions: [
      { id: 'bt1', name: 'Subsets', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/subsets/' },
      { id: 'bt2', name: 'Combination Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/combination-sum/' },
      { id: 'bt3', name: 'Permutations', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/permutations/' },
      { id: 'bt4', name: 'Subsets II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/subsets-ii/' },
      { id: 'bt5', name: 'Combination Sum II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/combination-sum-ii/' },
      { id: 'bt6', name: 'Word Search', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/word-search/' },
      { id: 'bt7', name: 'Palindrome Partitioning', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/palindrome-partitioning/' },
      { id: 'bt8', name: 'Letter Combinations of a Phone Number', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
      { id: 'bt9', name: 'N-Queens', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/n-queens/' },
      { id: 'bt10', name: 'Sudoku Solver', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/sudoku-solver/' },
      { id: 'bt11', name: 'Combination Sum III', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/combination-sum-iii/' },
      { id: 'bt12', name: 'Restore IP Addresses', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/restore-ip-addresses/' },
    ]
  },
  {
    id: 'trees', name: 'Ancient Grove', icon: '🌳', pattern: 'Trees',
    color: '#4ade80', group: 'Tree Kingdom', month: 3,
    artifact: { icon: '🍃', name: 'Living Branch', desc: 'Grows recursively, branching to reach every corner' },
    lore: 'Ancient trees whose roots and branches mirror the recursive beauty of tree structures.',
    questions: [
      { id: 'tr1', name: 'Invert Binary Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/invert-binary-tree/' },
      { id: 'tr2', name: 'Maximum Depth of Binary Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
      { id: 'tr3', name: 'Diameter of Binary Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
      { id: 'tr4', name: 'Balanced Binary Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/balanced-binary-tree/' },
      { id: 'tr5', name: 'Same Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/same-tree/' },
      { id: 'tr6', name: 'Subtree of Another Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/subtree-of-another-tree/' },
      { id: 'tr7', name: 'Lowest Common Ancestor of BST', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
      { id: 'tr8', name: 'Binary Tree Level Order Traversal', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
      { id: 'tr9', name: 'Binary Tree Right Side View', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
      { id: 'tr10', name: 'Count Good Nodes in Binary Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
      { id: 'tr11', name: 'Validate Binary Search Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/validate-binary-search-tree/' },
      { id: 'tr12', name: 'Kth Smallest Element in BST', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
      { id: 'tr13', name: 'Construct Binary Tree from Preorder and Inorder Traversal', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
      { id: 'tr14', name: 'Binary Tree Maximum Path Sum', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
      { id: 'tr15', name: 'Serialize and Deserialize Binary Tree', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
      { id: 'tr16', name: 'Binary Tree Zigzag Level Order Traversal', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/' },
      { id: 'tr17', name: 'Populating Next Right Pointers in Each Node', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/' },
    ]
  },
  {
    id: 'bst', name: 'Royal Arboretum', icon: '🏯', pattern: 'BST',
    color: '#4ade80', group: 'Tree Kingdom', month: 3,
    artifact: { icon: '🌿', name: 'Sorted Vine', desc: 'Maintains perfect order in every branch' },
    lore: 'The royal gardens where every tree is perfectly ordered by decree of the ancient king.',
    questions: [
      { id: 'bst1', name: 'Search in a Binary Search Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/search-in-a-binary-search-tree/' },
      { id: 'bst2', name: 'Insert into a Binary Search Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/insert-into-a-binary-search-tree/' },
      { id: 'bst3', name: 'Delete Node in a BST', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/delete-node-in-a-bst/' },
      { id: 'bst4', name: 'Validate Binary Search Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/validate-binary-search-tree/' },
      { id: 'bst5', name: 'Kth Smallest Element in BST', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
      { id: 'bst6', name: 'Lowest Common Ancestor of Binary Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/' },
      { id: 'bst7', name: 'Convert Sorted Array to Binary Search Tree', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/' },
      { id: 'bst8', name: 'Balance a Binary Search Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/balance-a-binary-search-tree/' },
    ]
  },
  {
    id: 'dfs', name: 'Spider Frontier', icon: '🕸️', pattern: 'DFS / Graph',
    color: '#9b7eff', group: 'Graph Realm', month: 3,
    artifact: { icon: '🕷️', name: 'Spider Silk', desc: 'Weaves a web across every connected node' },
    lore: 'A vast web of connections — explore every strand before retreating.',
    questions: [
      { id: 'df1', name: 'Number of Islands', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-islands/' },
      { id: 'df2', name: 'Clone Graph', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/clone-graph/' },
      { id: 'df3', name: 'Max Area of Island', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/max-area-of-island/' },
      { id: 'df4', name: 'Pacific Atlantic Water Flow', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
      { id: 'df5', name: 'Surrounded Regions', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/surrounded-regions/' },
      { id: 'df6', name: 'Rotting Oranges', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/rotting-oranges/' },
      { id: 'df7', name: 'Walls and Gates', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/walls-and-gates/' },
      { id: 'df8', name: 'Course Schedule', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/course-schedule/' },
      { id: 'df9', name: 'Course Schedule II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/course-schedule-ii/' },
      { id: 'df10', name: 'Redundant Connection', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/redundant-connection/' },
      { id: 'df11', name: 'Word Ladder', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/word-ladder/' },
      { id: 'df12', name: 'Alien Dictionary', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/alien-dictionary/' },
      { id: 'df13', name: 'Network Delay Time', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/network-delay-time/' },
    ]
  },
  {
    id: 'bfs', name: 'Sky Routes', icon: '☁️', pattern: 'BFS / Graph',
    color: '#4fc3f7', group: 'Graph Realm', month: 3,
    artifact: { icon: '🪁', name: 'Sky Compass', desc: 'Charts the shortest path through any network' },
    lore: 'Sky routes that spread outward like ripples — always finding the shortest way.',
    questions: [
      { id: 'bf1', name: 'Number of Islands', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-islands/' },
      { id: 'bf2', name: 'Rotting Oranges', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/rotting-oranges/' },
      { id: 'bf3', name: 'Walls and Gates', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/walls-and-gates/' },
      { id: 'bf4', name: 'Word Ladder', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/word-ladder/' },
      { id: 'bf5', name: 'Nearest Exit from Entrance in Maze', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/nearest-exit-from-entrance-in-maze/' },
      { id: 'bf6', name: 'Snakes and Ladders', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/snakes-and-ladders/' },
      { id: 'bf7', name: 'Open the Lock', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/open-the-lock/' },
      { id: 'bf8', name: 'Jump Game III', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/jump-game-iii/' },
      { id: 'bf9', name: 'Cheapest Flights Within K Stops', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/' },
    ]
  },
  {
    id: 'dsu', name: 'Union Sanctum', icon: '🔮', pattern: 'Disjoint Set Union',
    color: '#f0c060', group: 'Graph Realm', month: 3,
    artifact: { icon: '🪬', name: 'Union Amulet', desc: 'Unites any two elements into one family' },
    lore: 'A sanctum where all things are connected — Union-Find reveals invisible bonds between nodes.',
    questions: [
      { id: 'ds1', name: 'Number of Connected Components', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/' },
      { id: 'ds2', name: 'Redundant Connection', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/redundant-connection/' },
      { id: 'ds3', name: 'Graph Valid Tree', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/graph-valid-tree/' },
      { id: 'ds4', name: 'Accounts Merge', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/accounts-merge/' },
      { id: 'ds5', name: 'Number of Provinces', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-provinces/' },
      { id: 'ds6', name: 'Regions Cut By Slashes', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/regions-cut-by-slashes/' },
    ]
  },
  {
    id: 'greedy', name: 'Fortune Bazaar', icon: '💰', pattern: 'Greedy',
    color: '#fbbf24', group: 'Graph Realm', month: 3,
    artifact: { icon: '🎪', name: 'Fortune Dice', desc: 'Always picks the locally best trade, which wins the world' },
    lore: 'A bazaar of endless trades — the greedy merchant who always takes the best deal now wins in the end.',
    questions: [
      { id: 'gr1', name: 'Jump Game', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/jump-game/' },
      { id: 'gr2', name: 'Jump Game II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/jump-game-ii/' },
      { id: 'gr3', name: 'Gas Station', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/gas-station/' },
      { id: 'gr4', name: 'Hand of Straights', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/hand-of-straights/' },
      { id: 'gr5', name: 'Merge Triplets to Form Target Triplet', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/' },
      { id: 'gr6', name: 'Partition Labels', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/partition-labels/' },
      { id: 'gr7', name: 'Valid Parenthesis String', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/valid-parenthesis-string/' },
      { id: 'gr8', name: 'Non-overlapping Intervals', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/non-overlapping-intervals/' },
      { id: 'gr9', name: 'Meeting Rooms II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/meeting-rooms-ii/' },
      { id: 'gr10', name: 'Candy', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/candy/' },
      { id: 'gr11', name: 'Minimum Number of Arrows to Burst Balloons', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/' },
    ]
  },
  {
    id: 'dp1', name: 'Time Chamber', icon: '⏳', pattern: '1D Dynamic Programming',
    color: '#ff6eb4', group: 'DP Citadel', month: 4,
    artifact: { icon: '⌛', name: 'Temporal Hourglass', desc: 'Freezes optimal subproblems in time for instant reuse' },
    lore: 'A chamber outside of time — where decisions made in the past ripple forward into the future.',
    questions: [
      { id: 'dp1a', name: 'Climbing Stairs', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/climbing-stairs/' },
      { id: 'dp1b', name: 'Min Cost Climbing Stairs', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
      { id: 'dp1c', name: 'House Robber', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/house-robber/' },
      { id: 'dp1d', name: 'House Robber II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/house-robber-ii/' },
      { id: 'dp1e', name: 'Longest Palindromic Substring', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-palindromic-substring/' },
      { id: 'dp1f', name: 'Palindromic Substrings', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/palindromic-substrings/' },
      { id: 'dp1g', name: 'Decode Ways', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/decode-ways/' },
      { id: 'dp1h', name: 'Coin Change', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/coin-change/' },
      { id: 'dp1i', name: 'Maximum Product Subarray', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/maximum-product-subarray/' },
      { id: 'dp1j', name: 'Word Break', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/word-break/' },
      { id: 'dp1k', name: 'Longest Increasing Subsequence', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
      { id: 'dp1l', name: 'Partition Equal Subset Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
      { id: 'dp1m', name: 'Number of Longest Increasing Subsequence', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/number-of-longest-increasing-subsequence/' },
      { id: 'dp1n', name: 'Minimum Path Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/minimum-path-sum/' },
    ]
  },
  {
    id: 'dp2', name: 'Echoing Vaults', icon: '🏛️', pattern: '2D Dynamic Programming',
    color: '#e85d3a', group: 'DP Citadel', month: 4,
    artifact: { icon: '🗺️', name: 'Grid Parchment', desc: 'Maps every possible path through a 2D problem space' },
    lore: 'Vaults where each chamber echoes the decisions from the row above.',
    questions: [
      { id: 'dp2a', name: 'Unique Paths', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/unique-paths/' },
      { id: 'dp2b', name: 'Longest Common Subsequence', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/longest-common-subsequence/' },
      { id: 'dp2c', name: 'Best Time to Buy and Sell Stock with Cooldown', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/' },
      { id: 'dp2d', name: 'Coin Change II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/coin-change-ii/' },
      { id: 'dp2e', name: 'Target Sum', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/target-sum/' },
      { id: 'dp2f', name: 'Interleaving String', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/interleaving-string/' },
      { id: 'dp2g', name: 'Longest Increasing Path in a Matrix', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/' },
      { id: 'dp2h', name: 'Distinct Subsequences', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/distinct-subsequences/' },
      { id: 'dp2i', name: 'Edit Distance', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/edit-distance/' },
      { id: 'dp2j', name: 'Burst Balloons', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/burst-balloons/' },
      { id: 'dp2k', name: 'Regular Expression Matching', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/regular-expression-matching/' },
      { id: 'dp2l', name: 'Unique Paths II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/unique-paths-ii/' },
      { id: 'dp2m', name: 'Triangle', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/triangle/' },
    ]
  },
  {
    id: 'trie', name: 'Whispering Spire', icon: '🗼', pattern: 'Trie',
    color: '#4ade80', group: 'DP Citadel', month: 4,
    artifact: { icon: '🔑', name: 'Prefix Key', desc: 'Unlocks any word by walking character by character' },
    lore: 'A towering spire where every word is etched letter by letter — shared paths, split at each branch.',
    questions: [
      { id: 'tr_1', name: 'Implement Trie (Prefix Tree)', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
      { id: 'tr_2', name: 'Design Add and Search Words Data Structure', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
      { id: 'tr_3', name: 'Word Search II', diff: 'Hard', xp: 30, url: 'https://leetcode.com/problems/word-search-ii/' },
      { id: 'tr_4', name: 'Replace Words', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/replace-words/' },
      { id: 'tr_5', name: 'Search Suggestions System', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/search-suggestions-system/' },
      { id: 'tr_6', name: 'Maximum XOR of Two Numbers in an Array', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/' },
      { id: 'tr_7', name: 'Implement Magic Dictionary', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/implement-magic-dictionary/' },
    ]
  },
  {
    id: 'bitmanip', name: 'Binary Forge', icon: '⚡', pattern: 'Bit Manipulation',
    color: '#a78bfa', group: 'DP Citadel', month: 4,
    artifact: { icon: '🔩', name: 'XOR Wrench', desc: 'Cancels duplicates and reveals hidden structure with a single gate' },
    lore: 'A forge where numbers are stripped to their essence — raw bits that encode the truth beneath the surface.',
    questions: [
      { id: 'bm1', name: 'Single Number', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/single-number/' },
      { id: 'bm2', name: 'Number of 1 Bits', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/number-of-1-bits/' },
      { id: 'bm3', name: 'Counting Bits', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/counting-bits/' },
      { id: 'bm4', name: 'Reverse Bits', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/reverse-bits/' },
      { id: 'bm5', name: 'Missing Number', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/missing-number/' },
      { id: 'bm6', name: 'Sum of Two Integers', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/sum-of-two-integers/' },
      { id: 'bm7', name: 'Reverse Integer', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/reverse-integer/' },
      { id: 'bm8', name: 'Power of Two', diff: 'Easy', xp: 5, url: 'https://leetcode.com/problems/power-of-two/' },
      { id: 'bm9', name: 'Subsets (Bitmask approach)', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/subsets/' },
      { id: 'bm10', name: 'Single Number II', diff: 'Medium', xp: 15, url: 'https://leetcode.com/problems/single-number-ii/' },
    ]
  },
];

export const REALM_PROGRESSION = [
  'arrays', 'hashing', 'twoptr', 'sliding', 'prefix', 'bsearch',
  'linked', 'stack', 'heap', 'backtrack',
  'trees', 'bst', 'dfs', 'bfs', 'dsu', 'greedy',
  'dp1', 'dp2', 'trie', 'bitmanip',
];
